#!/bin/sh

# keyboard
setxkbmap -layout pt

# DPMS & session lock
xset dpms 240 0 0
xss-lock -- screenlock &

# compositor & background
picom &
wallpaper-cycle &

# notifications
dunst &

# media auto-mounting
udiskie &

# system tray
nm-applet &
blueman-applet &
cbatticon -r 3 -c 'systemctl hibernate' &
volumeicon &
redshift-gtk &
