#!/bin/sh

# keyboard
setxkbmap -layout pt

# DPMS & session lock
xset dpms 240 0 0
xss-lock -- screenlock &

# display
picom &
nitrogen --restore
unclutter &

# notifications
dunst &

# media auto-mounting
udiskie &

# system tray
nm-applet &
blueman-applet &
cbatticon -c 'systemctl hibernate' -l 15 -r 3 &
