#!/bin/bash

export_alias() {                                                                                                       
  # see <https://github.com/direnv/direnv/issues/73>

  local name=$1                                                                                                        
  shift                                                                                                                
  local alias_dir=$PWD/.direnv/aliases                                                                                 
  local target="$alias_dir/$name"                                                                                      
  mkdir -p "$alias_dir"                                                                                                
  if ! [[ ":$PATH:" == *":$alias_dir:"* ]]; then                                                                       
    PATH_add "$alias_dir"                                                                                              
  fi                                                                                                                   
                                                                                                                       
  echo "#!/usr/bin/env -S bash -e" > "$target"
  echo "$@" >> "$target"                                                                                               
  chmod +x "$target"                                                                                                   
}

