#!/bin/bash

# see <https://github.com/direnv/direnv/issues/73>
export_alias() {                                                                                                       
  local name=$1                                                                                                        
  shift                                                                                                                
  local alias_dir=$PWD/.direnv/aliases                                                                                 
  local target="$alias_dir/$name"                                                                                      
  mkdir -p "$alias_dir"                                                                                                
  if ! [[ ":$PATH:" == *":$alias_dir:"* ]]; then                                                                       
    PATH_add "$alias_dir"                                                                                              
  fi                                                                                                                   
                                                                                                                       
  echo "#!/usr/bin/env bash" > "$target"
  echo "$@" >> "$target"                                                                                               
  chmod +x "$target"                                                                                                   
}

# see <https://github.com/direnv/direnv/issues/73>
export_function() {
  local name=$1
  local alias_dir=$PWD/.direnv/aliases
  local target="$alias_dir/$name"
  mkdir -p "$alias_dir"
  if ! [[ ":$PATH:" == *":$alias_dir:"* ]]; then
    PATH_add "$alias_dir"
  fi

  if declare -f "$name" >/dev/null; then
    echo "#!/usr/bin/env bash" > "$target"
    declare -f "$name" >> "$target" 2>/dev/null
    echo "$name" >> "$target"
    chmod +x "$target"
  fi
}

layout_uv() {
  if [[ -d ".venv" ]]; then
    VIRTUAL_ENV="$(pwd)/.venv"
  fi

  if [[ -z $VIRTUAL_ENV || ! -d $VIRTUAL_ENV ]]; then
    log_status "No virtual environment exists. Executing \`uv venv\` to create one."
    uv venv
    VIRTUAL_ENV="$(pwd)/.venv"
  fi

  PATH_add "$VIRTUAL_ENV/bin"
  export UV_ACTIVE=1  # or VENV_ACTIVE=1
  export VIRTUAL_ENV
}
