general.import = ["/home/tlgs/.config/alacritty/colorscheme.toml"]

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 12

[font.normal]
family = "monospace"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 10
y = 10
